config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'dashboard/index'
  end

  get 'home/dashboard'
  get "contact_us" => "home#contact_us"
  post "save_contact" => "home#save_contact"
  get "save_contact" => "home#contact_us"

  resources :home
  root 'home#dashboard'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do 
   get '/dashboard' => "dashboard#index", :as => :root
    resources :users do
     collection do 
       get :agent_list
       get :customer_list
      end
    end
    resources :insurance_companies   
    resources :insurance_types  
 end
  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end
  DynamicRouter.load
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'
  	
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<!-- /. NAV SIDE  -->
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="col-lg-12">
        <h2>ADMIN DASHBOARD</h2>
      </div>
    </div>
    <!-- /. ROW  -->
    <hr />
    <div class="row">
      <div class="col-lg-12 ">
      </div>
    </div>
    <!-- /. ROW  --> 
    <div class="row text-center pad-top">
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="<%= admin_insurance_types_url %>" >
            <i class="fa fa-tasks fa-4x"></i>
            <h4>Insurance Type</h4>
          </a>
        </div>
      </div>
  <!--     <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-circle-o-notch fa-5x"></i>
            <h4>Check Data</h4>
          </a>
        </div>
      </div> -->
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-envelope-o fa-5x"></i>
            <h4>Mail Box</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-lightbulb-o fa-5x"></i>
            <h4>New Issues</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <%= link_to agent_list_admin_users_path do %>
          <i class="fa fa-users fa-5x"></i> 
          <h4>See Agents</h4>
          <% end %>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-key fa-5x"></i>
            <h4>Admin </h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-comments-o fa-5x"></i>
            <h4>Support</h4>
          </a>
        </div>
      </div>
    </div>
    <!-- /. ROW  --> 
    <div class="row text-center pad-top">
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-clipboard fa-5x"></i>
            <h4>All Docs</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-gear fa-5x"></i>
            <h4>Settings</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-wechat fa-5x"></i>
            <h4>Live Talk</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-bell-o fa-5x"></i>
            <h4>Notifications </h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-rocket fa-5x"></i>
            <h4>Launch</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <%= link_to customer_list_admin_users_path do %>
          <i class="fa fa-users fa-5x"></i> 
          <h4>See Customers</h4>
          <% end %>
        </div>
      </div>
    </div>
    <!-- /. ROW  -->    
    <div class="row text-center pad-top">
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-envelope-o fa-5x"></i>
            <h4>Mail Box</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-lightbulb-o fa-5x"></i>
            <h4>New Issues</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-users fa-5x"></i>
            <h4>See Users</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-key fa-5x"></i>
            <h4>Admin </h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="#" >
            <i class="fa fa-comments-o fa-5x"></i>
            <h4>Support</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-circle-o-notch fa-5x"></i>
            <h4>Check Data</h4>
          </a>
        </div>
      </div>
    </div>
    <!-- /. ROW  -->  
    <div class="row text-center pad-top">
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-rocket fa-5x"></i>
            <h4>Launch</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-clipboard fa-5x"></i>
            <h4>All Docs</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-gear fa-5x"></i>
            <h4>Settings</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-wechat fa-5x"></i>
            <h4>Live Talk</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-bell-o fa-5x"></i>
            <h4>Notifications </h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <%= link_to admin_insurance_companies_path do %>
          <i class="fa fa-users fa-5x"></i> 
          <h4>See Insurance Companies</h4>
          <% end %>
        </div>
      </div>
    </div>
    <!-- /. ROW  -->  
    <div class="row text-center pad-top">
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-lightbulb-o fa-5x"></i>
            <h4>New Issues</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-users fa-5x"></i>
            <h4>See Users</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-key fa-5x"></i>
            <h4>Admin </h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-comments-o fa-5x"></i>
            <h4>Support</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-circle-o-notch fa-5x"></i>
            <h4>Check Data</h4>
          </a>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
        <div class="div-square">
          <a href="blank.html" >
            <i class="fa fa-envelope-o fa-5x"></i>
            <h4>Mail Box</h4>
          </a>
        </div>
      </div>
    </div>
    <!-- /. ROW  -->   
    <div class="row">
      <div class="col-lg-12 ">
        <br/>
      </div>
    </div>
    <!-- /. ROW  --> 
  </div>
  <!-- /. PAGE INNER  -->
</div>
<!-- /. PAGE WRAPPER  -->
</div>