config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'dashboard/index'
  end

  get 'home/dashboard'
  get "contact_us" => "home#contact_us"
  post "save_contact" => "home#save_contact"
  get "save_contact" => "home#contact_us"

  resources :home
  root 'home#dashboard'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do 
   get '/dashboard' => "dashboard#index", :as => :root
    resources :users do
     collection do 
       get :agent_list
       get :customer_list
      end
    end
    resources :insurance_companies   
    resources :insurance_types  
 end
  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end
  DynamicRouter.load
end

app/controllers/admin/insurance_types_controller.rb
class Admin::InsuranceTypesController < ApplicationController
  layout 'admin', :except => [:show]
  before_action :authenticate_user!
  before_action :set_insurance_type, only: [:show, :edit, :update, :destroy]

  def index
    @insurance_types = InsuranceType.all.decorate
  end


  def show
  end

  
  def new
    @insurance_type = InsuranceType.new
  end


  def edit
  end


  def create
    @insurance_type = InsuranceType.new(insurance_type_params)

    respond_to do |format|
      if @insurance_type.save
        format.html { redirect_to admin_insurance_types_path(@insurance_type), notice: 'Insurance type was successfully created.' }
        format.json { render :show, status: :created, location: @insurance_type }
      else
        format.html { render :new }
        format.json { render json: @insurance_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @insurance_type.update(insurance_type_params)
        format.html { redirect_to admin_insurance_types_path(@insurance_type), notice: 'Insurance type was successfully updated.' }
        format.json { render :show, status: :ok, location: @insurance_type }
      else
        format.html { render :edit }
        format.json { render json: @insurance_type.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    binding.pry
    @insurance_type.soft_delete
    respond_to do |format|
      format.html { redirect_to admin_insurance_types_url, notice: 'Insurance type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_insurance_type
      @insurance_type = InsuranceType.find(params[:id]).decorate
    end


    def insurance_type_params
      params.require(:insurance_type).permit(:name, :description, :parent_id)
    end
end

app/controllers/insurance_types_controller.rb
class InsuranceTypesController < ApplicationControlleref

end

app/helpers/insurance_types_helper.rb
module InsuranceTypesHelper
end

app/views/admin/insurance_types/_form.html.erb
<%= form_for([:admin,insurance_type]) do |f| %>
  <% if insurance_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(insurance_type.errors.count, "error") %> prohibited this insurance_type from being saved:</h2>

      <ul>
      <% insurance_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.cktext_area :description %>
  </div>

  <div class="field">
    <%= f.label :parent_id %>
    <%= f.select :parent_id, InsuranceType.roots.pluck(:name,:id), {:include_blank => "Parent"} %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active, :checked => true %>
  </div>  

  <div class="actions">
    <%= f.submit "Submit" ,class: "btn btn-primary" %>
    <%= link_to 'Cancel', admin_insurance_types_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/insurance_types/edit.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
        <div class="col-lg-12 col-md-12">
          <h3> Edit Insurance Type </h3>	
          <%= render 'form', insurance_type: @insurance_type %>
        </div>
    </div>
  </div>
</div>

app/views/admin/insurance_types/index.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row-fluid">
      <h3> Insurance Type Management</h3>
      <div class="col-lg-12 col-md-12">
         <div class="row">
           <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table">
             <tr>
               <td>
                 <%= link_to 'New Insurance Type', new_admin_insurance_type_path,class: "btn btn-primary" %>
               </td>
             </tr>
           </table>
         </div>
         <div class="row">
           <table class="table table-striped table-bordered table-hover">
             <thead>
               <tr>
                 <th> Name </th>
                 <th> Parent </th>
                 <th> Active </th>
                 <th> External Url </th>
                 <th> Actions </th>
               </tr>
             </thead>
             <tbody>
               <% @insurance_types.each do |insurance_type| %>
                 <tr>
                   <td> <%= link_to insurance_type.name, admin_insurance_type_path(insurance_type) %> </td>
                   <td> <%= insurance_type.parent? %> </td>
                   <td> <%= insurance_type.active %> </td>
                   <td> <%= insurance_type.permalink_url %> </td>
                   <td>
                     <%= link_to 'Edit', edit_admin_insurance_type_path(insurance_type) , :class => "btn" %>
                     <%= link_to 'Destroy', admin_insurance_type_path(insurance_type), method: :delete, data: { confirm: 'Are you sure?' } %>
                   </td>
                 </tr>
               <% end %>
             </tbody>
           </table>
         </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/insurance_types/new.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
        <div class="col-lg-12 col-md-12">
          <h3> New Insurance Type </h3>	
          <%= render 'form', insurance_type: @insurance_type %>
        </div>
    </div>
  </div>
</div>

app/views/admin/insurance_types/show.html.erb
<% if current_user.admin? %>
	<div class="container">
	  <div class="col-12">
	  	<div class="row-fluid">
	   	 <%= link_to "Edit", edit_admin_insurance_type_path(@insurance_type), class: "btn btn-primary pul-right" %>
	 
		</div>
	  </div>
	</div>
<% end %>	
<%= @insurance_type.description.html_safe %>