config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  namespace :admin do
    get 'dashboard/index'
  end

  get 'home/dashboard'
  get "contact_us" => "home#contact_us"
  post "save_contact" => "home#save_contact"
  get "save_contact" => "home#contact_us"

  resources :home
  root 'home#dashboard'
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do 
   get '/dashboard' => "dashboard#index", :as => :root
    resources :users do
     collection do 
       get :agent_list
       get :customer_list
      end
    end
    resources :insurance_companies   
    resources :insurance_types  
 end
  as :user do
      patch '/user/confirmation' => 'confirmations#update', :via => :patch, :as => :update_user_confirmation
  end
  DynamicRouter.load
end

app/models/insurance_company.rb
class InsuranceCompany < ApplicationRecord
   mount_uploader :logo, LogoUploader
   validates :company_name, :licence_no,:company_code, :company_address, :contact_number, 
      	:registration_code, :authorised_person_name, :authorised_person_contact_number, :authorised_person_contact_email, :designation, presence: true
end

app/controllers/admin/insurance_companies_controller.rb
class Admin::InsuranceCompaniesController < ApplicationController
	layout 'admin'
	before_action :authenticate_user!
  before_action :set_insurance_companies, only: [:edit, :update, :destroy, :show]
    
    load_and_authorize_resource

  def index
  	@insurance_companies = InsuranceCompany.all
  end

  def new
  	@insurance_company = InsuranceCompany.new
  end

  def create
     
     @insurance_company = InsuranceCompany.create(insurance_company_params)
     
     respond_to do |format|
       if @insurance_company.save   
         format.html { redirect_to admin_insurance_companies_path, notice: 'Insurance Company was successfully created.'  }
       else
         format.html { render :action => "new" }
       end
     end
  end

  def edit
    
  end

  def update
 
   @insurance_company =  @insurance_company.update(insurance_company_params)

    respond_to do |format|
      if @insurance_company
        format.html { redirect_to admin_insurance_companies_path, notice: 'Insurance Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @insurance_company.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end 

  def destroy
     @insurance_company.destroy
     respond_to do |format|
       format.html { redirect_to(admin_insurance_companies_path,  notice: 'Insurance Company was successfully deleted.') }
       format.xml  { head :ok }
     end
  end

  private 
    def set_insurance_companies
      @insurance_company = InsuranceCompany.find(params[:id])
    end 

    def insurance_company_params
      params.required(:insurance_company).permit(:company_name, :licence_no,:company_code, :company_address, :contact_number, 
      	:registration_code, :authorised_person_name, :authorised_person_contact_number, :authorised_person_contact_email, :designation, :status, :logo)
    end
end

app/helpers/admin/insurance_companies_helper.rb
module Admin::InsuranceCompaniesHelper
end

app/views/admin/insurance_companies/edit.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
        <div class="col-lg-6 col-md-12">
<h3> Edit Insurance Company</h3>
<%= form_for [:admin, @insurance_company], html: {id: "edit_insurance_company", multipart: true } do |f| %>
  <% for message in @insurance_company.errors.full_messages %>
    <%= message %><br/>
  <% end %>
    <div>
      <label for="company_name">Company Name</label>
      <div>
        <%= f.text_field :company_name, value: @insurance_company.try(:company_name) %>
      </div>
    </div>
    <div>
      <label for="licence_no">Licence No</label>
      <div>
        <%= f.text_field :licence_no, value: @insurance_company.try(:licence_no) %>
      </div>
    </div>
    <div>
      <label for="company_code">Company Code</label>
      <div>
        <%= f.text_field :company_code, value: @insurance_company.try(:company_code) %>
      </div>
    </div>
    <div>
      <label for="contact_number">Company Address</label>
      <div>
        <%= f.text_area :company_address, value: @insurance_company.try(:company_address) %>
      </div>
    </div>
    <div>
      <label for="name">Contact Number</label>
      <div>
        <%= f.text_field :contact_number, value: @insurance_company.try(:contact_number) %>
      </div>
    </div>
    <div>
      <label for="registration_code">Registration Code</label>
      <div>
        <%= f.text_field :registration_code, value:  @insurance_company.try(:registration_code) %>
      </div>
    </div>
      <div>
      <label for="authorised_person_name">Authorised Person Name</label>
      <div>
        <%= f.text_field :authorised_person_name, value: @insurance_company.try(:authorised_person_name) %>
      </div>
    </div>
     <div>
      <label for="authorised_person_contact_number">Authorised Person Contact Number</label>
      <div>
        <%= f.text_field :authorised_person_contact_number, value: @insurance_company.try(:authorised_person_contact_number) %>
      </div>
    </div>
    <div>
      <label for="authorised_person_contact_email">Email</label>
      <div>
        <%= f.text_field :authorised_person_contact_email, value: @insurance_company.try(:authorised_person_contact_email) %>
      </div>
    </div>
    <div>
      <label for="designation">Designation</label>
      <div>
        <%= f.text_field :designation, value: @insurance_company.try(:designation) %>
      </div>
    </div><br>
    <div>
      <div>
        <%= f.submit "Update", class: "btn btn-primary" %> <%= link_to 'Cancel', admin_insurance_companies_path, class: 'btn btn-danger' %>

      </div>
    </div>
<%end%>
</div>
</div>
</div>

app/views/admin/insurance_companies/index.html.erb
<!-- /. NAV SIDE  -->
<div id="page-wrapper" >
<div id="page-inner">
<div class="row">

<div class="col-lg-6 col-md-12">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td>
          <%= link_to "New Insurance Company", new_admin_insurance_company_path, class: "btn btn-primary" %>
        </td>
      </tr>
    </table>
    <br>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Company Name</th>
                <th>Licence No</th>
                <th>Company code</th>
                <th>Company Address</th>
                <th>Contact Number</th>
                <th>Registration Code</th>
                <th>Person Name</th>
                <th>Person Contact Number</th>
                <th>Person Contact Email</th>
                <th>Designation</th>
                <th>Status</th>
                <th>Logo</th>
                <th>Actions</th>
            </tr>
        </thead>
       <% @insurance_companies.each do |insurance_company,index |  %>
        <tbody>
          <tr>
            <td><%= link_to insurance_company.try(:company_name), admin_insurance_company_path(insurance_company) %></td>
            <td><%= insurance_company.try(:licence_no) %></td>
            <td><%= insurance_company.try(:company_code) %></td>
            <td><%= insurance_company.try(:company_address) %></td>
            <td><%= insurance_company.try(:contact_number) %></td>
            <td><%= insurance_company.try(:registration_code) %></td>
            <td><%= insurance_company.try(:authorised_person_name) %></td>
            <td><%= insurance_company.try(:authorised_person_contact_number) %></td>
            <td><%= insurance_company.try(:authorised_person_contact_email) %></td>
            <td><%= insurance_company.try(:designation) %></td>
            <td><%= insurance_company.try(:status) %></td>
            <td><%= image_tag(insurance_company.logo_url(:thumb).to_s) %></td>
            <td><%= link_to "Edit", edit_admin_insurance_company_path(insurance_company) , :class => "btn"%>
              | <%= link_to "Delete", admin_insurance_company_path(insurance_company), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        </tbody>
    <% end %> 
    </table>

</div>
</div>
</div>
</div>

app/views/admin/insurance_companies/new.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
        <div class="col-lg-6 col-md-12">
<h3> New Insurance Company</h3>
<%= form_for [:admin, @insurance_company], :html => {:id => "new_insurance_company",:multipart => true } do |f| %>
  <% for message in @insurance_company.errors.full_messages %>
    <%= message %><br/>
  <% end %>
    <div>
      <label for="company_name">Company Name</label>
      <div>
        <%= f.text_field :company_name ,:placeholder=>"company name"%>
      </div>
    </div>
    <div>
      <label for="licence_no">Licence No</label>
      <div>
        <%= f.text_field :licence_no ,:placeholder=>"licence no" %>
      </div>
    </div>
    <div>
      <label for="company_code">Company Code</label>
      <div>
        <%= f.text_field :company_code ,:placeholder=>"company code" %>
      </div>
    </div>
    <div>
      <label for="contact_number">Company Address</label>
      <div>
        <%= f.text_area :company_address ,:placeholder=>"company address"%>
      </div>
    </div>
    <div>
      <label for="name">Contact Number</label>
      <div>
        <%= f.text_field :contact_number ,:placeholder=>"contact number"%>
      </div>
    </div>
    <div>
      <label for="registration_code">Registration Code</label>
      <div>
        <%= f.text_field :registration_code ,:placeholder=>"registration code"%>
      </div>
    </div>
      <div>
      <label for="authorised_person_name">Authorised Person Name</label>
      <div>
        <%= f.text_field :authorised_person_name ,:placeholder=>"authorised person name"%>
      </div>
    </div>
     <div>
      <label for="authorised_person_contact_number">Authorised Person Contact Number</label>
      <div>
        <%= f.text_field :authorised_person_contact_number ,:placeholder=>"authorised person contact number"%>
      </div>
    </div>
    <div>
      <label for="authorised_person_contact_email">Email</label>
      <div>
        <%= f.text_field :authorised_person_contact_email ,:placeholder=>"authorised person contact email"%>
      </div>
    </div>
    <div>
      <label for="designation">Designation</label>
      <div>
        <%= f.text_field :designation ,:placeholder=>"designation"%>
      </div>
    </div>
    <div>
      <label for="designation">logo</label>
      <div>
        <%= f.file_field :logo %>
      </div>
    </div>

    <div><br>
      <div>
        <%= f.submit "Submit", class: "btn btn-primary"%> <%= link_to 'Cancel', admin_insurance_companies_path, class: 'btn btn-danger' %>
      </div>
    </div>
<%end%>
</div>
</div>
</div>

app/views/admin/insurance_companies/show.html.erb
<!-- /. NAV SIDE  -->
<div id="page-wrapper" >
<div id="page-inner">
<div class="row">

<div class="col-lg-6 col-md-12">
	<%= image_tag(@insurance_company.logo_url.to_s) %>
</div>
</div>
</div>
</div>